<?php
define("_ROOT","/debbane/");
define("pageDir","rtl");
define("mainDir", "right");
define("reverseDir", "left");
define("_Company","ÔÑßÉ ÏÈÇäå");
define("_OtherLang","English");
define("_CurrLang","ÇáÚÑÈíÉ");
define("_OtherLang_abbr","en");
define("_CurrLang_abbr","ar");

define("_Categories","ÃäæÇÚ ÇáãäÊÌÇÊ");
define("_username","ÇÓã ÇáãÓÊÎÏã");
define("_password","ßáãÉ ÇáãÑæÑ");
define("_forgotPW","äÓíÊ ßáãÉ ÇáãÑæÑ¿");
define("_Register","ÊÓÌíá");
define("_Home","ÇáÑÆíÓíÉ");
define("_about","Úä ÇáÔÑßÉ");
define("_News","ÇáÃÎÈÇÑ");
define("_Magazine","ÇáãÌáÉ");
define("_FAQs","ÃÓÆáÉ ÔÇÆÚÉ");
define("_contact","ÇÊÕá ÈäÇ");
define("_Profile","ÊÚÑíİ ÈÇáÔÑßÉ");
define("_Search","ÈÍË İí ãæŞÚ ÏÈÇäå ...");
define("_Links","ÑæÇÈØ");
define("_Copy","ÔÑßÉ ÏÈÇäå &copy;");
define("_PPolicy","ÇáÎÕæÕíÉ");
define("_PoweredBy",'ÈÏÚã ãä <a href="#" class="external-link">ãÌãæÚÉ İÇíä áÇíä</a>');
define("_Main_Categories","ÇáÊÕäíİÇÊ ÇáÃÓÇÓíÉ");
define("_Latest_News","ÂÎÑ ÇáÃÎÈÇÑ");
define("_read"," ÇáãÒíÏ");
define("_More_news","ÃÎÈÇÑ ÃÎÑì");
define("_Newsletter","ÇáÑÓÇáÉ ÇáÃÎÈÇÑíÉ");
define("_newsletter_msg","ÇÔÊÑß ÈÑÓÇáÊäÇ ÇáÃÎÈÇÑíÉ ááÍÕæá Úáì ÂÎÑ ÃÎÈÇÑ ÔÑßÊäÇ");
define("_nl_name","ÇÓãß");
define("_nl_email","ÈÑíÏß ÇáÇáßÊÑæäí");
define("_Follow_us","ÊÇÈÚäÇ");
define("_Follow_us_msg","ÊÇÈÚäÇ Úáì ÇáÔÈßÇÊ ÇáÇÌÊãÇÚíÉ ÇáÃßËÑ ÔíæÚÇğ:");
define("_Results","äÊÇÆÌ ÇáÈÍË");
define("News","ÇáÃÎÈÇÑ");
define("Categories","ÇáÊÕäíİÇÊ");
define("Products","ÇáãäÊÌÇÊ");
define("MagTitles","ÚäÇæíä ÇáãÌáÉ");
define("_search_msg","ÚÏÏ ÇáäÊÇÆÌ");
define("_no_results","áÇ íæÌÏ äÊÇÆÌ");
define("_issue_titles_of","ÅÕÏÇÑ ");
define("_Jan","ßÇäæä ÇáËÇäí");
define("_Feb","ÔÈÇØ");
define("_Mar","ÂĞÇÑ");
define("_Apr","äíÓÇä");
define("_May","ÃíÇÑ");
define("_Jun","ÍÒíÑÇä");
define("_Jul","ÊãæÒ");
define("_Aug","ÂÈ");
define("_Sep","Ãíáæá");
define("_Oct","ÊÔÑíä ÇáÃæá");
define("_Nov","ÊÔÑíä ÇáËÇäí");
define("_Dec","ßÇäæä ÇáÃæá");
define("_Download_Issue","ÊäÒíá ÇáÚÏÏ");
define("Previous","ÇáÓÇÈŞ");
define("Next","ÇáÊÇáí");
define("_mag_year","ÓäæÇÊ ÇáãÌáÉ");
define("_mag_issues","ÅÕÏÇÑÇÊ ÇáãÌáÉ");
define("_issue","ÅÕÏÇÑ : ");
define("_View_Titles","ÚäÇæíä ÇáÚÏÏ");
define("_Download_Title","ÊäÒíá ÇáãŞÇá");
define("_On","İí ");
define("_Back","ÑÌæÚ");
define("_details","áãÒíÏ ãä ÇáÊİÇÕíá");
define("_ClickHere","ÇÖÛØ åäÇ");
define("_EnterEmail","ÇÏÎá ÈÑíÏß ÇáÇáßÊÑæäí!");
define("_EnterName","ÇÏÎá ÇÓãß!");
define("_EmailDontMatchName","ÇáÈÑíÏ ÇáÇáßÊÑæäí æÇáÇÓã ÛíÑ ãÊØÇÈŞÇä!");
define("_Unsubscribtion_done","Êã ÅáÛÇÁ ÇáÇÔÊÑÇß!");
define("_Unsubscribtion_failed","İÔá ÅáÛÇÁ ÇáÇÔÊÑÇß!");
define("_Resubscribtion_done","ÊãÊ ÅÚÇÏÉ ÇáÇÔÊÑÇß!");
define("_Resubscribtion_failed","İÔáÊ ÅÚÇÏÉ ÇáÇÔÊÑÇß!");
define("_Subscribtion_done","Êã ÇáÇÔÊÑÇß!");
define("_Subscribtion_failed","İÔá ÇáÇÔÊÑÇß!");

//define("","");
define("_FName","ÇáÇÓã");
define("_LName","ÇáßäíÉ");
define("_DOB","ÊÇÑíÎ ÇáãíáÇÏ");
define("_Certificate","ÇáÔåÇÏÉ");
define("_Position","ÇáãäÕÈ");
define("_Employer","ãßÇä ÇáÚãá");
define("_EMail","ÇáÈÑíÏ ÇáÇáßÊÑæäí");
define("_POBOX","ÕäÏæŞ ÇáÈÑíÏ");
define("_Street","ÇáÔÇÑÚ");
define("_City","ÇáãÏíäÉ");
define("_Country","ÇáÈáÏ");
define("_Phone","ÇáåÇÊİ");
define("_Mobile","ÇáÌæÇá");
define("_RequiredFields","(*) ãä ÇáÖÑæÑí ÅãáÇÁ ÇáÍŞæá ÇáÊí ÚáíåÇ ÚáÇãÉ ÈãÚáæãÇÊ ÕÍíÍÉ ÍíË áÇ íãßä ÊİÚíá ÇáÊÓÌíá ãÇ áã Êßä ÇáãÚáæãÇÊ ÏŞíŞÉ ææÇÖÍÉ");
define("_ActiveEMail","(**) íÌÈ Úáíß æÖÚ Åíãíáß ÇáİÚÇá áäÊãßä ãä ÅÑÓÇá ßáãÉ ÇáÓÑ áß ÚÈÑå");
define("_ProvideMobile","(***) ãä ÎáÇá ÅÚØÇÆäÇ ÑŞã åÇÊİß ÇáÌæÇá äÖãä áß ÇáÍÕæá Úáì ãÚáæãÇÊ ÌÏíÏÉ ÏæãÇ Úä ãäÊÌÇÊ ÇáÔÑßÉ æãæÇÏåÇ æÎÏãÇÊåÇ ÚÈÑ ÑÓÇÆá SMS áÇ ÊÊÑÏÏ İí ÅÚØÇÆäÇ ÑŞã ÌæÇáß ÇáÕÍíÍ");
define("_RegisterationMessageTitle","ÊİÚíá ÍÓÇÈ ãæŞÚ ÔÑßÉ ÏÈÇäå");
define("_RegisterationMessage","ãÑÍÈÇ ##USER##, <br/>ÃäÊ ÇáÂä ãÓÌøá áÏíäÇ åÇ åí ßáãÉ ÇáãÑæÑ (##PASS##) ÇáÊí ãä ÎáÇáåÇ ÓÊÊãßä ãä ÇáÏÎæá Åáì ÍÓÇÈß Úáì ãæŞÚ <a href='http://www.debbane-sy.net'>ÔÑßÉ ÏÈÇäå</a>");
define("_forgotPWTitle","ÇÓÊÑÌÇÚ ßáãÉ ÇáãÑæÑ");
define("_RecoverPasswordMsg","ÃÏÎá ÇÓã ÇáãÓÊÎÏã æÈÑíÏß ÇáÇáßÊÑæäí ÇáĞí ÇÓÊÎÏãÊå ááÊÓÌíá æÓäÑÓá áß ßáãÉ ãÑæÑ ÌÏíÏÉ");
define("_RecoverPasswordMSGTitle","ãæŞÚ ÔÑßÉ ÏÈÇäå - ÇÓÊÑÌÇÚ ßáãÉ ÇáãÑæÑ");
define("_RecoverPasswordEMail","ãÑÍÈÇ ##USER##, <br/>ßáãÉ ÇáãÑæÑ ÇáÌÏíÏÉ åí : (##PASS##)");
define("_RegisterationFailed","İÔá ÇáÊÓÌíá");
define("_PWChangeFailed","İÔá ÊÛííÑ ßáãÉ ÇáãÑæÑ");
define("_EmailSendFailed","İÔá ÅÑÓÇá ÇáÑÓÇáÉ ");
define("_UserEmailNotMatch","ÇÓã ÇáãÓÊÎÏã æÇáÈÑíÏ ÇáÇáßÊÑæäí ÛíÑ ãÊØÇÈŞíä");
define("_EnterUsername","ÃÏÎá ÇÓã ÇáãÓÊÎÏã!");
define("_EnterPassword","ÃÏÎá ßáãÉ ÇáãÑæÑ!");
define("_LoginFailed","İÔá ÊÓÌíá ÇáÏÎæá ÍÇæá ãÑÉ ÃÎÑì!");
define("_WelcomeUser", "ãÑÍÈÇ <i>##USER##</i> (<a class='loadLink' href='../users/changePassword.php'>ÊÛííÑ ßáãÉ ÇáãÑæÑ</a> | <a href='../users/logout.php'>ÎÑæÌ</a>)");
define("_ChangePass","ÊÛííÑ ßáãÉ ÇáãÑæÑ");
define("_OldPass","ÃÏÎá ßáãÉ ÇáãÑæÑ ÇáÍÇáíÉ");
define("_NewPass","ÃÏÎá ßáãÉ ÇáãÑæÑ ÇáÌÏíÏÉ");
define("_ConfirmPass","ÃÏÎá ÊÃßíÏ ßáãÉ ÇáãÑæÑ");
define("_PasswordConfirmationError", "ßáãÉ ÇáãÑæÑ ÇáÌÏíÏÉ æÊÃßíÏ ßáãÉ ÇáãÑæÑ íÌÈ Ãä íÊØÇÈŞÇ");
define("_WrongPassword", "ßáãÉ ÇáãÑæÑ ÇáãÏÎáÉ ÎÇØÆÉ");
define("_Change", "ÊÛííÑ");
define("_Careers","æÙÇÆİ");
define("_View","ÚÑÖ");
define("_öApply","ÊŞÏã");
define("_forDept"," áŞÓãã");
define("_Responsibilities","ÇáãÓÄæáíÇÊ");
define("_Qualifications","ÇáãÄåáÇÊ");
define('Your_name','ÇÓãß');
define('Your_email','ÈÑíÏß ÇáÅáßÊÑæäí');
define('Friend_name','ÇÓã ÕÏíŞß');
define('Friend_email','ÇáÈÑíÏ ÇáÅáßÊÑæäí áÕÏíŞß');
define("_Send","ÃÑÓá");
define("_Cancel","ÅáÛÇÁ");
define("STF_MESSAGE","ãÑÍÈÇ ##FNAME##,<br/>ÕÏíŞß ##NAME## íÑíÏß Ãä ÊáŞí äÙÑÉ Úáì åĞÇ ÇáãÍÊæì ãä ãæŞÚ "._Company.".<br/>áÑÄíÉ åĞÇ ÇáãÍÊæì ÃÖÛØ <a href='##LINK##'>åäÇ</a>");
define("STF_DONE","Êã ÅÑÓÇá ÇáÑÓÇáÉ ÈäÌÇÍ!");
define("STF_FAILED","áã íÊã ÅÑÓÇá ÇáÑÓÇáÉ!");
define("Message_from_your_friend","ÑÓÇáÉ ãä ÕÏíŞß");
define("unsubscribe_note","áÅáÛÇÁ ÇáÇÔÊÑÇß ÃÏÎá ÇÓãß æ ÈÑíÏß ÇáÇáßÊÑæäí ÇáĞíä ŞãÊ ÈÇáÇÔÊÑÇß ÈåãÇ.");
define("_FileDoesNotExist","<h1>404 Çáãáİ ÛíÑ ãæÌæÏ</h1><p>ÚĞÑÇğ Çáãáİ ÇáãØáæÈ ÛíÑ ãæÌæÏ! <br/>íÑÌì ÇáÊÃßÏ ãä ÇáæÕáÉ!</p>");
define("_OldLinkNote","áãÒíÏ ãä ÇáãÚáæãÇÊ ÇáÚáãíÉ");
define("_ApplicationFailed","İÔá ÇáÊŞÏã áİÑÕÉ ÇáÚãá");
define("_Apply","ÍİÙ");
define("_ApplyToJob","ÊŞÏã áİÑÕÉ ÇáÚãá");
define("_FullName","ÇáÇÓã ÇáßÇãá");
define("_YourPhoto","ÕæÑÊß ÇáÔÎÕíÉ");
define("_Attach1","ÇáãÑİŞ ÇáÃæá");
define("_Attach2","ÇáãÑİŞ ÇáËÇäí");
define("_Attach3","ÇáãÑİŞ ÇáËÇáË");
define("_Fax","ÇáİÇßÓ");
define("_Address","ÇáÚäæÇä");
define("_Subject","ÇáãæÖæÚ");
define("_Comments","ÇáÑÓÇáÉ");
?>