<?php
define("_ROOT","/debbane/");
define("pageDir","ltr");
define("mainDir", "left");
define("reverseDir", "right");
define("_Company","Debbane Co.");
define("_OtherLang","ÇáÚÑÈíÉ");
define("_CurrLang","English");
define("_OtherLang_abbr","ar");
define("_CurrLang_abbr","en");

define("_Categories","Products Categories");
define("_username","Username");
define("_password","Password");
define("_forgotPW","Forgot password");
define("_Register","Register");
define("_Home","Home");
define("_about","About us");
define("_News","News");
define("_Magazine","Magazine");
define("_FAQs","FAQs");
define("_contact","Contact us");
define("_Profile","Profile");
define("_Search","Search in Debbane website ...");
define("_Links","Links");
define("_Copy","Debbane Co. &copy;");
define("_PPolicy","Privacy Policy");
define("_PoweredBy",'Powered by <a href="#" class="external-link">Fineline Group</a>');
define("_Main_Categories","Main Categories");
define("_Latest_News","Latest News");
define("_read"," read");
define("_More_news","More news");
define("_Newsletter","Newsletter");
define("_newsletter_msg","Subscribe to our newsletter to get the latest news about our company");
define("_nl_name","Your name");
define("_nl_email","Your e-mail address");
define("_Follow_us","Follow us");
define("_Follow_us_msg","Follow us on the most popular social networks:");
define("_Results","Search Results");
define("News","News");
define("Categories","Categories");
define("Products","Products");
define("MagTitles","Magazine Title");
define("_search_msg","Total number of results");
define("_no_results","No results");
define("_issue_titles_of","Issue Titles of");
define("_Jan","January");
define("_Feb","February");
define("_Mar","March");
define("_Apr","April");
define("_May","May");
define("_Jun","June");
define("_Jul","July");
define("_Aug","August");
define("_Sep","September");
define("_Oct","October");
define("_Nov","November");
define("_Dec","December");
define("_Download_Issue","Download Issue");
define("Previous","Previous");
define("Next","Next");
define("_mag_year","Magazine Issues - Years");
define("_mag_issues","Magazine Issues");
define("_issue","Issue : ");
define("_View_Titles","View Titles");
define("_Download_Title","Download Title");
define("_On","on");
define("_Back","Back");
define("_details","For detailed catalogue");
define("_ClickHere","click here");
define("_EnterEmail","Enter your e-mail address please!");
define("_EnterName","Enter your name please!");
define("_EmailDontMatchName","E-Mail and name do not match!");
define("_Unsubscribtion_done","Unsubscribtion done successfully!");
define("_Unsubscribtion_failed","Failed to unsubscribe!");
define("_Resubscribtion_done","Re-subscribtion done successfully!");
define("_Resubscribtion_failed","Failed to re-subscribe!");
define("_Subscribtion_done","Subscribtion done successfully!");
define("_Subscribtion_failed","Failed to subscribe!");

define("_Fax","Fax");
define("_Address","Address");
define("_Subject","Subject");
define("_Comments","Comments");
define("_FName","First Name");
define("_LName","Last Name");
define("_DOB","Date of Birth");
define("_Certificate","Certificate");
define("_Position","Position");
define("_Employer","Employer");
define("_EMail","E-Mail");
define("_POBOX","P.O.Box");
define("_Street","Street");
define("_City","City");
define("_Country","Country");
define("_Phone","Phone");
define("_Mobile","Mobile");
define("_RequiredFields","(*) It is important to fill these fields with correct and accurate information to activate your account.");
define("_ActiveEMail","(**) You should provide an active E-Mail address, the password of your account will be sent to this E-Mail.");
define("_ProvideMobile","(***) When you give us your mobile number we gurintee you get always new information about our products and services via SMS. Do not hesitate to give us your mobile number");
define("_RegisterationMessageTitle","Debbane Website Account Activation");
define("_RegisterationMessage","Hello ##USER##, <br/>You are now registered in our website Here is the password (##PASS##) by which you can sign in to your account on <a href='http://www.debbane-sy.net'>Debbane Website</a>");
define("_forgotPWTitle","Recover Password");
define("_RecoverPasswordMsg","Enter your username and registeration E-Mail and we will send you a new password");
define("_RecoverPasswordMSGTitle","Debbane Website - Password Recovery");
define("_RecoverPasswordEMail","Hello ##USER##, <br/>Your new password is : (##PASS##)");
define("_RegisterationFailed","Failed to register");
define("_PWChangeFailed","Failed to change password");
define("_EmailSendFailed","Failed to send e-mail");
define("_UserEmailNotMatch","Username and E-Mail address do not match");
define("_EnterUsername","Enter your username !");
define("_EnterPassword","Enter your password !");
define("_LoginFailed","Login failed, try again!");
define("_WelcomeUser", "Welcome <i>##USER##</i> (<a class='loadLink' href='../users/changePassword.php'>Change Password</a> | <a href='../users/logout.php'>Logout</a>)");
define("_ChangePass","Change Password");
define("_OldPass","Enter current password");
define("_NewPass","Enter a new password");
define("_ConfirmPass","Confirm the new password");
define("_PasswordConfirmationError", "New password and password confirmation must be the same");
define("_WrongPassword", "Wrong password");
define("_Change", "Change");
define("_Careers","Careers");
define("_View","View");
define("_Apply","Apply");
define("_forDept","for the department of");
define("_Responsibilities","Responsibilities");
define("_Qualifications","Qualifications");
define('Your_name','Your name');
define('Your_email','Your email');
define('Friend_email','Friend email');
define('Friend_name','Friend name');
define("_Send","Send");
define("_Cancel","Cancel");
define("STF_MESSAGE","Hi ##FNAME##,<br/>Your friend ##NAME## wants you to have look on this content from "._Company.".<br/>To see the content click <a href='##LINK##'>here</a>");
define("STF_DONE","Message sent!");
define("STF_FAILED","Failed to send message!");
define("Message_from_your_friend","Message from your friend");
define("unsubscribe_note","To unsubscribe enter your name and E-mail that you used to subscribe.");
define("_FileDoesNotExist","<h1>404 File not found</h1><p>Sorry, requested file does not exist!<br/>Check the link please.</p>");
define("_OldLinkNote","For more scientific info ");
define("_ApplicationFailed","Failed to apply to job offer");
define("_ApplyToJob","Apply to Job");
define("_FullName","Full name");
define("_YourPhoto","Your photo");
define("_Attach1","1st Attachment");
define("_Attach2","2nd Attachment");
define("_Attach3","3rd Attachment");

?>